

# TODO: calculate the precision and recall of classification performance
# 
#' @param score : The predicted score vector calculated from the classification model
#' @param label : The actual label value, the class label must be 1 or 0, and be of numeric type
#' @param threshold : When the predicted score is greater than or equal to this value, it is considered positive
#' 
PerformancePR <- function(score, label, threshold=0.5) 
{
	predict.label <- as.numeric(score >=  threshold);
	
	TP <- sum((label == predict.label) & (label == 1));
	FP <- sum((label != predict.label) & (label == 0));
	FN <- sum((label != predict.label) & (label == 1));		
	
	precision <- TP/(TP+FP);
	recall = TP/(TP+FN);
	
	return(c(precision=precision, recall=recall))
}

##======================================================================================



# TODO: Calculate the average performance measures for different prediction scores under each threshold 
#       based on the threshold vector generated by the step size
#
#' @param scoreList: A list storing predicted scores
#' @param labelList: A list storing the actual label value
#' @param from: The starting value of threshold
#' @param to : The end value of the threshold
#' @param step: step size
#' 
#' 
MeanPerformancePR <- function(scoreList, labelList, from=1, to=0, step=0.01)
{
	if(length(scoreList) != length(labelList)){
		stop("scoreList与labelList without the same length")
	}
	
#	if(length(scoreList) == 1){
#		stop("length is 1，not using PerformanceMetricsList")
#	}
	
	thresholds = seq(from, to, by=step) 
	
	
	num.element = length(scoreList);
	
	results = sapply(thresholds, function(x){
				temp = sapply(1:num.element, function(i){
							PerformancePR(scoreList[[i]], labelList[[i]], x)
						})
				temp = rowMeans(temp, na.rm=TRUE);
				return(temp)
			})
	
	results <- t(results)
	Fmeasure  <- round((2 * results[,"precision"] * results[,"recall"])/(results[,"precision"] + results[,"recall"]), 3)
	thresholds <- thresholds
	
	results <- cbind(results, Fmeasure, thresholds)
	
	return(results)
}









